import {beforeAll,afterAll,describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import type {D1Database} from '@cloudflare/workers-types';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {cloud} from '../worker/cloud';
import {newPlan} from '../src/model';
let mf:Miniflare,db:D1Database;
const owner='owner@example.test',origin='https://sketch.example.test';
const sha=async(b:BufferSource)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b)),n=>n.toString(16).padStart(2,'0')).join('');
function request(path:string,method='GET',body?:unknown,who=owner){return cloud(new Request(origin+'/api'+path,{method,headers:{Origin:origin,'X-Sketch-Client':'2','Content-Type':body instanceof ArrayBuffer?'application/octet-stream':'application/json'},body:body===undefined?undefined:body instanceof ArrayBuffer?body:JSON.stringify(body)}),db,who);}
async function upload(data:unknown,media='application/json'){const bytes=new TextEncoder().encode(JSON.stringify(data)),hashes=[await sha(bytes)],id=await sha(new TextEncoder().encode(hashes.join('')+':'+bytes.length));expect((await request('/blobs','POST',{id,hashes,bytes:bytes.length,media,name:'test.json'})).status).toBe(200);expect((await request('/blobs/'+id+'/0','PUT',bytes.buffer)).status).toBe(200);expect((await request('/blobs/'+id+'/complete','POST',{})).status).toBe(200);return id;}
beforeAll(async()=>{mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:'export default {fetch(){return new Response("test")}}',compatibilityDate:'2026-09-19',d1Databases:['DB'],log:undefined}));db=await mf.getD1Database('DB') as unknown as D1Database;await db.exec(readFileSync(new URL('../migrations/0001_cloud.sql',import.meta.url),'utf8'));},30000);
afterAll(async()=>{await mf?.dispose();});
describe('実データベースでの保存・認証・復元',()=>{
 it('別サイトからの書き込みを拒否する',async()=>{const r=await cloud(new Request(origin+'/api/blobs',{method:'POST',body:'{}'}),db,owner);expect(r.status).toBe(403);});
 it('未完成・破損した分割ファイルを公開しない',async()=>{const bytes=new TextEncoder().encode('fixture'),hashes=[await sha(bytes)],id=await sha(new TextEncoder().encode(hashes.join('')+':'+bytes.length));await request('/blobs','POST',{id,hashes,bytes:bytes.length,media:'image/png',name:'test.png'});expect((await request('/blobs/'+id+'/complete','POST',{})).status).toBe(409);expect((await request('/blobs/'+id+'/0','PUT',new Uint8Array(7).buffer)).status).toBe(400);expect((await request('/blobs/'+id)).status).toBe(409);});
 it('保存して他端末が取得でき、別利用者には見えない',async()=>{const doc=newPlan('同期の検証'),payload=await upload({plan:doc});const res=await request('/plans/'+doc.id,'PUT',{payload,expectedRevision:0,operation:payload+'_0'});expect(res.status).toBe(200);expect((await res.json() as any).revision).toBe(1);expect((await request('/plans/'+doc.id)).status).toBe(200);expect((await request('/plans/'+doc.id,'GET',undefined,'other')).status).toBe(404);expect((await request('/blobs/'+payload,'GET',undefined,'other')).status).toBe(404);});
 it('同じ保存の再送は二重保存しない',async()=>{const doc=newPlan(),payload=await upload({plan:doc}),body={payload,expectedRevision:0,operation:payload+'_0'};await request('/plans/'+doc.id,'PUT',body);const again=await request('/plans/'+doc.id,'PUT',body);expect((await again.json() as any).revision).toBe(1);});
 it('2台が同じ版から保存すると片方だけ成功する',async()=>{const doc=newPlan(),a=await upload({plan:{...doc,name:'A'}}),b=await upload({plan:{...doc,name:'B'}});const r=await Promise.all([request('/plans/'+doc.id,'PUT',{payload:a,expectedRevision:0,operation:a+'_0'}),request('/plans/'+doc.id,'PUT',{payload:b,expectedRevision:0,operation:b+'_0'})]);expect(r.map(v=>v.status).sort()).toEqual([200,409]);});
 it('10版を保持し、履歴の原本参照を維持する',async()=>{const doc=newPlan();for(let n=0;n<12;n++){const payload=await upload({plan:{...doc,name:'版'+n}});expect((await request('/plans/'+doc.id,'PUT',{payload,expectedRevision:n,operation:payload+'_'+n})).status).toBe(200);}const data=await (await request('/plans/'+doc.id+'/history')).json() as any;expect(data.versions).toHaveLength(10);expect(data.versions[0].revision).toBe(12);expect(data.versions[9].revision).toBe(3);});
 it('無料容量の上限で新しい書き込みだけを止める',async()=>{const who='quota-test';await db.prepare("INSERT INTO blobs(owner,id,bytes,parts,hashes,media,name,created) VALUES(?,?,?,?,?,?,?,?)").bind(who,'a'.repeat(64),400*1024*1024,1,'[]','image/png','quota',new Date().toISOString()).run();const bytes=new TextEncoder().encode('x'),hashes=[await sha(bytes)],id=await sha(new TextEncoder().encode(hashes.join('')+':'+bytes.length));expect((await request('/blobs','POST',{id,hashes,bytes:bytes.length,media:'image/png',name:'test'},who)).status).toBe(507);});
});
