// @vitest-environment jsdom
import {act,createRef} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {Stage,type Tool} from '../src/Stage';
import {newPlan,element,type Plan} from '../src/model';
let host:HTMLDivElement,root:Root,changes:Plan[],plan:Plan;
beforeEach(()=>{vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);vi.stubGlobal('ResizeObserver',class{observe(){}disconnect(){}});Object.defineProperty(SVGElement.prototype,'setPointerCapture',{configurable:true,value:()=>{}});vi.spyOn(SVGElement.prototype,'getBoundingClientRect').mockReturnValue({x:0,y:0,left:0,top:0,width:800,height:600,right:800,bottom:600,toJSON(){}});host=document.createElement('div');document.body.appendChild(host);root=createRoot(host);plan=newPlan();changes=[];});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();vi.restoreAllMocks();vi.unstubAllGlobals();});
async function render(tool:Tool,touchDraw=false){await act(async()=>{root.render(<Stage doc={plan} tool={tool} figure="rect" part="car" color="#303e34" lineWidth={25} snapping={false} touchDraw={touchDraw} selected="" onSelect={()=>{}} onChange={f=>changes.push(f(plan))} onScale={()=>{}} onText={()=>{}} onTool={()=>{}} onHint={()=>{}} svgRef={createRef<SVGSVGElement>()} fitSignal={0}/>);});return host.querySelector('svg[data-testid]')!;}
async function pointer(target:globalThis.Element,type:string,id:number,pointerType:string,x:number,y:number){await act(async()=>{const event=new Event(type,{bubbles:true});for(const [key,value] of Object.entries({pointerId:id,pointerType,clientX:x,clientY:y,button:0}))Object.defineProperty(event,key,{value});target.dispatchEvent(event);});}
it('指で描くOFFの1本指は線を作らない',async()=>{const svg=await render('pen');await pointer(svg,'pointerdown',1,'touch',100,100);await pointer(svg,'pointermove',1,'touch',300,300);await pointer(svg,'pointerup',1,'touch',300,300);expect(changes).toHaveLength(0);});
it('指で描くONなら指の線を保存する',async()=>{const svg=await render('pen',true);await pointer(svg,'pointerdown',1,'touch',100,100);await pointer(svg,'pointermove',1,'touch',300,300);await pointer(svg,'pointerup',1,'touch',300,300);expect(changes).toHaveLength(1);expect(changes[0].elements[0].kind).toBe('stroke');});
it('ペンで描いている間の手のひら接触は線を消さない',async()=>{const svg=await render('pen');await pointer(svg,'pointerdown',1,'pen',100,100);await pointer(svg,'pointermove',1,'pen',300,300);await pointer(svg,'pointerdown',2,'touch',400,400);await pointer(svg,'pointerup',2,'touch',400,400);await pointer(svg,'pointerup',1,'pen',300,300);expect(changes).toHaveLength(1);expect(changes[0].elements[0].points).toHaveLength(2);});
it('2本指の拡大開始で部品の仮配置を取り消す',async()=>{const svg=await render('part');await pointer(svg,'pointerdown',1,'touch',100,100);await pointer(svg,'pointerdown',2,'touch',300,300);await pointer(svg,'pointermove',2,'touch',400,400);await pointer(svg,'pointerup',2,'touch',400,400);await pointer(svg,'pointerup',1,'touch',100,100);expect(changes).toHaveLength(0);});
it('指で描くOFFでも1本指の部品配置はできる',async()=>{const svg=await render('part');await pointer(svg,'pointerdown',1,'touch',100,100);await pointer(svg,'pointerup',1,'touch',100,100);expect(changes[0].elements[0].part).toBe('car');});
it('固定した線を消しゴムで消さない',async()=>{plan.elements=[{...element('stroke',[{x:0,y:0},{x:1000,y:1000}]),locked:true}];await render('erase');const line=host.querySelector('[data-element]')!;await pointer(line,'pointerdown',1,'mouse',100,100);await pointer(line,'pointerup',1,'mouse',100,100);expect(changes).toHaveLength(0);});
it('入力が中断された線は確定しない',async()=>{const svg=await render('pen');await pointer(svg,'pointerdown',1,'pen',100,100);await pointer(svg,'pointermove',1,'pen',300,300);await pointer(svg,'pointercancel',1,'pen',300,300);await pointer(svg,'pointerup',1,'pen',300,300);expect(changes).toHaveLength(0);});
