import {useEffect,useRef,useState,type ReactNode} from 'react';
import {FolderOpen,FileUp,Plus,Pencil,MousePointer2,Ruler,PaintBucket,Trees,MoveHorizontal,Type,Hand,Undo2,Redo2,Download,Copy,Trash2,RotateCw,HelpCircle,X,Save,Settings2,FileJson,CheckCircle2,Cloud,Search,Layers,Archive,ArrowUp,ArrowDown,Eraser} from 'lucide-react';
import {usePlan} from './usePlan';
import {Stage,type Tool} from './Stage';
import {type Plan,type Point,type Part,type Element,type Material,parts,materials,uid,newPlan,calibrated,distance,moved,withLength,element,area,cleanStroke,rotateElement,resizeElement,bounds,calibrateUnderlay} from './model';
import {samplePlan} from './samples';
import {listPlans,putOriginal} from './storage';
import {readSource,underlay,exportBackup,importBackup,createExport,shareOrDownload,type ExportResult,type SourceImage} from './io';
import {thumbnail} from './render';
import {SourceDialog} from './SourceDialog';
import {UnderlaySettings} from './UnderlaySettings';
import {cloudStatus,synchronize,history,fetchCloudPlan,maintenance,pendingSyncCount,resolveConflict,type CloudStatus} from './cloud';
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} onCancel={e=>{e.preventDefault();close();}}><div className="modal-head"><h2>{title}</h2><button onClick={close} aria-label="閉じる"><X size={20}/></button></div>{children}</dialog>;}
function NumberField({label,value,apply,min=1,max=1000000}:{label:string;value:number;apply:(n:number)=>void;min?:number;max?:number}){const [v,setV]=useState(String(Math.round(value)));useEffect(()=>setV(String(Math.round(value))),[value]);const commit=()=>{const n=Number(v);if(v.trim()&&Number.isFinite(n)&&n>=min&&n<=max){if(Math.abs(n-value)>.001)apply(n);}else setV(String(Math.round(value)));};return <label className="field"><span>{label}</span><input type="number" min={min} max={max} value={v} onChange={e=>setV(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></label>;}
const toolInfo:{id:Tool;label:string;icon:typeof Pencil;hint:string}[]=[
{id:'select',label:'選択',icon:MousePointer2,hint:'図形を選択して移動。丸いハンドルで形を調整'},
{id:'pen',label:'手書き',icon:Pencil,hint:'ペンで自由に描く。線の終わりで少し止めると形を整えます'},
{id:'clean',label:'清書',icon:Ruler,hint:'直線・四角・円はドラッグ。折れ線・面は角を順に押します'},
{id:'finish',label:'仕上げ',icon:PaintBucket,hint:'面を選び、素材と濃さを設定'},
{id:'part',label:'部品',icon:Trees,hint:'部品を選び、図面を押して配置'},
{id:'dimension',label:'寸法',icon:MoveHorizontal,hint:'2点をドラッグして実寸を表示'},
{id:'text',label:'注記',icon:Type,hint:'図面を押して、打ち合わせメモを追加'},
{id:'pan',label:'移動',icon:Hand,hint:'ドラッグで移動。2本指で移動・拡大縮小'},
{id:'erase',label:'消す',icon:Eraser,hint:'消したい手書き線を押す。元に戻せます'}];
const colors=['#303e34','#282828','#b64b42','#bd813a','#4674a2','#528267','#91775c','#ffffff'];
export default function App(){
 const plan=usePlan(),{doc}=plan;
 const change=(fn:(p:Plan)=>Plan,record=true)=>{try{plan.change(fn,record);return true;}catch(e){setMessage(e instanceof Error?e.message:'変更できませんでした');return false;}};
 const [route,setRoute]=useState<'list'|'editor'>('list'),[items,setItems]=useState<Plan[]>([]),[tool,setTool]=useState<Tool>('select'),[selected,setSelected]=useState(''),[figure,setFigure]=useState<'line'|'polyline'|'rect'|'ellipse'|'area'>('line'),[part,setPart]=useState<Part>('car');
 const [color,setColor]=useState('#303e34'),[lineWidth,setLineWidth]=useState(25),[snapping,setSnapping]=useState(true),[touchDraw,setTouchDraw]=useState(()=>localStorage.getItem('sketch-touch-draw')==='true'),[panel,setPanel]=useState(()=>window.innerWidth>=1000),[message,setMessage]=useState(''),[busy,setBusy]=useState(''),[fitSignal,setFitSignal]=useState(0),[search,setSearch]=useState(''),[showArchived,setShowArchived]=useState(false),[limit,setLimit]=useState(48);
 const [dialog,setDialog]=useState<'new'|'scale'|'text'|'help'|'export'|'history'|null>(null),[entry,setEntry]=useState(''),[scaleTarget,setScaleTarget]=useState<'all'|'underlay'>('all'),[scalePoints,setScalePoints]=useState<Point[]>([]),[textPoint,setTextPoint]=useState<Point>({x:0,y:0}),[pdfSize,setPdfSize]=useState<'A4'|'A3'>('A4'),[includeDraft,setIncludeDraft]=useState(true),[format,setFormat]=useState<'pdf'|'png'>('pdf'),[output,setOutput]=useState<ExportResult|null>(null);
 const [source,setSource]=useState<Awaited<ReturnType<typeof readSource>>|null>(null),[cloud,setCloud]=useState<CloudStatus>({available:false}),[cloudText,setCloudText]=useState('接続を確認中'),[conflicts,setConflicts]=useState<string[]>([]),[versions,setVersions]=useState<{revision:number;payload:string;updated:string}[]>([]);
 const sourceInput=useRef<HTMLInputElement>(null),backupInput=useRef<HTMLInputElement>(null),svgRef=useRef<SVGSVGElement>(null),syncBusy=useRef(false),autoSync=useRef<()=>Promise<boolean>>(async()=>false),initialSync=useRef(false);
 const picked=doc?.elements.find(e=>e.id===selected),toolMeta=toolInfo.find(t=>t.id===tool);
 const fail=(e:unknown)=>setMessage(e instanceof Error?e.message:'操作に失敗しました');
 const refresh=async()=>{try{setItems(await listPlans());}catch(e){fail(e);}};
 useEffect(()=>{if(route==='list')void refresh();},[route]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),15000);return()=>clearTimeout(t);},[message]);
 useEffect(()=>{void cloudStatus().then(s=>{setCloud(s);setCloudText(s.available?'同期できます':'端末保存・バックアップ');});const warning=(e:Event)=>setMessage((e as CustomEvent).detail);window.addEventListener('storage-warning',warning);return()=>window.removeEventListener('storage-warning',warning);},[]);
 useEffect(()=>{localStorage.setItem('sketch-touch-draw',String(touchDraw));},[touchDraw]);
 useEffect(()=>{setOutput(null);},[doc,pdfSize,includeDraft,format]);
 const open=async(p:Plan,skip=false)=>{try{await plan.load(p,skip);setRoute('editor');setSelected('');setTool('select');setPanel(window.innerWidth>=1000);}catch(e){fail(e);}};
 const toList=async()=>{try{await plan.flush();setRoute('list');}catch(e){fail(e);}};
 const update=(patch:Partial<Element>)=>{if(picked?.locked&&patch.locked===undefined)return;change(d=>({...d,elements:d.elements.map(e=>e.id===selected?{...e,...patch}:e)}));};
 const remove=()=>{if(picked?.locked)return;change(d=>({...d,elements:d.elements.filter(e=>e.id!==selected)}));setSelected('');};
 const duplicate=()=>{if(picked){const copy={...moved(picked,300,300),id:uid(),locked:false};change(d=>({...d,elements:[...d.elements,copy]}));setSelected(copy.id);}};
 const duplicatePlan=()=>{if(doc)void open({...doc,id:uid(),revision:0,archived:false,name:(doc.name+'（別案）').slice(0,120)},!!plan.error);};
 const reorder=(front:boolean)=>{if(!picked||picked.locked)return;change(d=>({...d,elements:front?[...d.elements.filter(e=>e.id!==selected),picked]:[picked,...d.elements.filter(e=>e.id!==selected)]}));};
 const cleanSelected=()=>{if(!picked||picked.kind!=='stroke')return;const cleaned={...cleanStroke(picked),id:uid()};change(d=>({...d,elements:[...d.elements,cleaned],draftOpacity:.25}));setSelected(cleaned.id);setTool('select');};
 async function runSync(pull=false){
  if(cloud.publicPreview){if(pull)setMessage(cloud.error||'開発中は端末保存とバックアップを利用してください');return false;}
  if(syncBusy.current)return false;syncBusy.current=true;const openedId=doc?.id;
  if(pull)setBusy('案件を同期中');setCloudText('同期中');
  try{await plan.flush();const result=await synchronize(pull);setConflicts(result.conflicts);setCloud(await cloudStatus());const pending=await pendingSyncCount();setCloudText(result.conflicts.length?'更新の競合があります':pending?'同期待ち '+pending+'件':'クラウド保存済み');
   if(pull){const updated=await listPlans();setItems(updated);const fresh=updated.find(v=>v.id===openedId);if(fresh&&route==='editor'&&!result.conflicts.includes(fresh.id))await plan.load(fresh);if(!result.conflicts.length)setMessage('最新の案件を同期しました');}
   return pending===0;
  }catch(e){setCloudText(e instanceof Error?e.message:'同期できません。端末保存は継続します');if(pull)fail(e);return false;}finally{syncBusy.current=false;if(pull)setBusy('');}
 }
 autoSync.current=()=>runSync(false);
 useEffect(()=>{if(cloud.available&&!initialSync.current){initialSync.current=true;void runSync(true);}},[cloud.available]);
 useEffect(()=>{let timer:ReturnType<typeof setTimeout>|undefined,dirty=false,checking=false,generation=0,retryAt=0,delay=30000;
  const attempt=async()=>{if(!dirty||checking||Date.now()<retryAt)return;checking=true;const version=generation;const ok=await autoSync.current();checking=false;if(ok&&version===generation){dirty=false;delay=30000;}else{retryAt=Date.now()+delay;delay=Math.min(delay*2,300000);}};
  const saved=()=>{dirty=true;generation++;retryAt=0;setCloudText('同期待ち');clearTimeout(timer);timer=setTimeout(()=>void attempt(),5000);};
  const online=()=>{dirty=true;retryAt=0;void attempt();};const interval=setInterval(()=>void attempt(),30000);
  window.addEventListener('plan-saved',saved);window.addEventListener('online',online);return()=>{clearTimeout(timer);clearInterval(interval);window.removeEventListener('plan-saved',saved);window.removeEventListener('online',online);};
 },[]);
 async function resolveBoth(id:string){setBusy('両方の変更を保存中');try{await plan.flush();const latest=await resolveConflict(id);if(doc?.id===id)await plan.load(latest);setConflicts(v=>v.filter(x=>x!==id));await refresh();setMessage('この端末の変更を別案に残し、元の案件をクラウドの最新版へ更新しました');}catch(e){fail(e);}finally{setBusy('');}}
 useEffect(()=>{const keyboard=(e:KeyboardEvent)=>{const t=e.target as HTMLElement;if(t.closest('input,textarea,select')||t.isContentEditable||document.querySelector('dialog[open]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();void plan.flush().catch(fail);}if(route!=='editor')return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?plan.redo():plan.undo();}if(e.key==='Delete'&&picked)remove();if(e.key==='Escape'){setTool('select');setSelected('');}};window.addEventListener('keydown',keyboard);return()=>window.removeEventListener('keydown',keyboard);},[plan,route,picked]);
 async function chooseSource(file?:File){if(!file)return;setBusy('下絵を読み込み中');try{if(source)await source.close();setSource(await readSource(file));}catch(e){fail(e);}finally{setBusy('');}}
 async function applySource(rendered:SourceImage,page:number,mode:'new'|'replace',scale:boolean){
  if(!source)return;const file=source.file.type?source.file:new File([source.file],source.file.name,{type:'application/pdf'}),assetId=await putOriginal(file),u={...underlay(rendered,file.name+' / '+page+'ページ'),assetId,page};
  if(mode==='replace'&&doc){const old=doc.underlay;if(old){u.x=old.x||0;u.y=old.y||0;u.rotation=old.rotation||0;u.height=u.height*old.width/u.width;u.width=old.width;}if(!change(d=>({...d,underlay:u})))return;setFitSignal(v=>v+1);}
  else{await plan.load({...newPlan(file.name.replace(/\.[^.]+$/,'').slice(0,120)),calibrated:false,underlay:u});setRoute('editor');}
  await source.close();setSource(null);setSelected('');setScaleTarget('all');setTool(scale?'scale':'pen');setPanel(false);setMessage(scale?'寸法が分かる2点を押してください':'下絵を固定しました。ペンで上から描けます。指で描く場合は設定をONにしてください');
 }
 async function closeSource(){const s=source;setSource(null);if(s)await s.close();}
 async function loadPublicSample(){setBusy('公開サンプルを読み込み中');try{const response=await fetch('/samples/exterior-plan.pdf');if(!response.ok)throw Error('サンプルを取得できませんでした');await chooseSource(new File([await response.blob()],'公開サンプル_外構平面図.pdf',{type:'application/pdf'}));}catch(e){fail(e);}finally{setBusy('');}}
 async function backupFile(file?:File){if(!file)return;setBusy('編集データを読み込み中');try{await open(await importBackup(file));}catch(e){fail(e);}finally{setBusy('');}}
 async function makeOutput(){if(!doc)return;setBusy('出力プレビューを作成中');try{await plan.flush();setOutput(await createExport(doc,pdfSize,includeDraft,format));}catch(e){fail(e);}finally{setBusy('');}}
 async function submitDialog(){try{if(dialog==='new')await open(newPlan(entry.trim()||'新しい外構プラン'));if(dialog==='text'){const el={...element('text',[textPoint]),text:entry.trim(),color};if(el.text){change(d=>({...d,elements:[...d.elements,el]}));setSelected(el.id);}setTool('select');}if(dialog==='scale'&&doc){const next=scaleTarget==='underlay'?calibrateUnderlay(doc,scalePoints[0],scalePoints[1],Number(entry)):calibrated(doc,scalePoints[0],scalePoints[1],Number(entry));if(scaleTarget==='all'&&doc.calibrated&&doc.elements.length)await open({...next,id:uid(),revision:0,name:(doc.name+'（縮尺補正）').slice(0,120)});else change(()=>next);setFitSignal(v=>v+1);setTool('select');setMessage('基準寸法を設定しました。別の既知寸法でも照合してください');}setDialog(null);}catch(e){fail(e);}}
 async function showHistory(){if(!doc)return;setBusy('保存履歴を確認中');try{setVersions(await history(doc.id));setDialog('history');}catch(e){fail(e);}finally{setBusy('');}}
 async function restore(payload:string){setBusy('履歴を別案として復元中');try{const old=await fetchCloudPlan(payload);await open({...old,id:uid(),revision:0,archived:false,name:(old.name+'（履歴から復元）').slice(0,120)});setDialog(null);}catch(e){fail(e);}finally{setBusy('');}}
 const matches=items.filter(p=>!!p.archived===showArchived&&(!search||[p.name,p.owner||''].join(' ').toLowerCase().includes(search.toLowerCase())));
 return <div className={'app '+(route==='editor'?'editor-app':'')}>
 <input ref={sourceInput} type="file" hidden accept="application/pdf,image/png,image/jpeg,image/webp" onChange={e=>{void chooseSource(e.target.files?.[0]);e.target.value='';}}/>
 <input ref={backupInput} type="file" hidden accept=".garden.zip,.garden.json,application/json,application/zip" onChange={e=>{void backupFile(e.target.files?.[0]);e.target.value='';}}/>
 <header className="app-header"><div className="brand"><span className="brand-mark"><Pencil size={22}/></span><div><strong>外構スケッチ</strong><small>下絵に描いて、プランを伝える。</small></div><span className="build-label">v0.2</span></div><div className="header-actions">{route==='editor'&&<button aria-label="案件一覧" onClick={()=>void toList()}><FolderOpen size={18}/><span>案件一覧</span></button>}<button onClick={()=>setDialog('help')} aria-label="使い方"><HelpCircle size={20}/></button>{route==='editor'&&<button className="primary" onClick={()=>{setOutput(null);setDialog('export');}}><Download size={18}/>出力</button>}</div></header>
 {message&&<div className="notice" role="status"><span>{message}</span><button aria-label="通知を閉じる" onClick={()=>setMessage('')}><X size={16}/></button></div>}
 {plan.error&&<div className="error-banner" role="alert"><strong>{plan.status}</strong><span>{plan.error}</span><button onClick={plan.retry}>再試行</button><button onClick={duplicatePlan}>別案に複製</button>{doc&&<button onClick={()=>void exportBackup(doc).catch(fail)}>データを退避</button>}</div>}
 {conflicts.length>0&&<div className="error-banner" role="alert"><span>同じ案件に2つの変更があります。この端末の変更を別案に残して、最新版を取り込めます。</span>{conflicts.map(id=><button key={id} onClick={()=>void resolveBoth(id)}>{(items.find(p=>p.id===id)?.name|| (doc?.id===id?doc.name:"案件")).slice(0,30)}：両方を残して解決</button>)}</div>}
 {route==='list'?<main className="projects"><div className="projects-heading"><div><div className="eyebrow">EXTERIOR PLANNING</div><h1>図面の上で、話を進める。</h1><p>配置図を読み込み、手描きから清書・素材・寸法まで。</p></div><button className="primary" onClick={()=>sourceInput.current?.click()}><FileUp size={19}/>下絵から始める</button></div>
 <div className="sync-banner"><Cloud size={20}/><div><strong>{cloud.available?cloudText:'この端末に自動保存'}</strong><p>{cloud.available?'PCとiPadで同じ案件を使うときは、同期完了後に「同期・再取得」を押してください。':(cloud.error||'クラウド接続の準備中です。編集データのバックアップを利用できます。')}</p>{cloud.bytes!==undefined&&<small>クラウド使用量 {Math.round(cloud.bytes/1048576)} / {Math.round((cloud.limit||0)/1048576)} MB</small>}</div><button onClick={()=>void runSync(true)}>同期・再取得</button></div>
 <div className="project-toolbar"><h2>{showArchived?'アーカイブ':'案件'} <span>{matches.length}</span></h2><div className="button-row"><button onClick={()=>{setEntry('');setDialog('new');}}><Plus size={17}/>白紙から</button><button onClick={()=>backupInput.current?.click()}><FileJson size={17}/>編集データを開く</button></div></div>
 <div className="list-filters"><label className="search-field"><Search size={18}/><input aria-label="案件名・担当者で検索" placeholder="案件名・担当者で検索" value={search} onChange={e=>{setSearch(e.target.value);setLimit(48);}}/></label><button aria-pressed={showArchived} onClick={()=>setShowArchived(v=>!v)}><Archive size={17}/>{showArchived?'通常の案件へ':'アーカイブ'}</button></div>
 <div className="project-grid">{matches.slice(0,limit).map(p=><button className="project-card" key={p.id} onClick={()=>void open(p)}><div className="project-thumbnail"><img src={thumbnail(p)} alt={p.name+'のプラン'}/><span>{p.elements.length} 要素</span></div><strong>{p.name}</strong><small>{p.owner?p.owner+' · ':''}{new Date(p.updatedAt).toLocaleString('ja-JP',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</small></button>)}
 {!showArchived&&<><button className="sample-card" onClick={()=>void loadPublicSample()}><FileUp size={30}/><strong>実際の下絵で試す</strong><span>公開されている外構図PDF・2ページ</span><span className="sample-link">ページを選んで取り込む →</span></button><button className="sample-card compact" onClick={()=>void open(samplePlan())}><Trees size={28}/><strong>作図済みの見本を見る</strong><span>架空の配置図・車・植栽入り</span></button></>}</div>
 {matches.length>limit&&<button className="full" onClick={()=>setLimit(v=>v+48)}>さらに案件を表示</button>}
 <p className="small-note">下絵と編集内容を端末に保存します。作業の区切りでバックアップも保管してください。公開図面は社内の動作検証用です。</p></main>:
 doc&&<><div className="project-heading"><div className="project-title"><input aria-label="案件名" value={doc.name} maxLength={120} onChange={e=>change(d=>({...d,name:e.target.value}),false)}/><span className={'save-status '+(plan.status==='端末に保存済み'?'saved':'')} aria-live="polite">{plan.status==='端末に保存済み'?<CheckCircle2 size={14}/>:<Save size={14}/>}<span>{plan.status}</span></span></div><div className="button-row"><button onClick={()=>sourceInput.current?.click()}><FileUp size={16}/>下絵</button><button className={!doc.calibrated?'attention':''} onClick={()=>{setScaleTarget('all');setTool('scale');setPanel(true);}}><Ruler size={16}/>基準寸法</button><button onClick={()=>setPanel(v=>!v)} aria-label={panel?'設定を隠す':'設定を表示'} aria-pressed={panel}><Settings2 size={18}/></button></div></div>
 <main className={'workspace '+(!panel?'hide-inspector':'')}><nav className="tool-rail" aria-label="作図ツール">{toolInfo.map(t=><button key={t.id} aria-pressed={tool===t.id} onClick={()=>{setTool(t.id);if(['clean','part','finish'].includes(t.id))setPanel(true);}}><t.icon size={21}/><span>{t.label}</span></button>)}</nav>
 <div className="work-center"><div className="workflow-bar"><div className="button-row"><button onClick={()=>change(d=>({...d,layers:{draft:true,design:true,dimensions:true},draftOpacity:.8}))}>下描き</button><button onClick={()=>change(d=>({...d,layers:{draft:true,design:true,dimensions:true},draftOpacity:.25}))}>清書を確認</button><button onClick={()=>change(d=>({...d,layers:{...d.layers,draft:false}}))}>仕上がり</button></div><label className="touch-toggle"><input type="checkbox" checked={touchDraw} onChange={e=>setTouchDraw(e.target.checked)}/>指で描く</label></div>
 <Stage doc={doc} tool={tool} figure={figure} part={part} color={color} lineWidth={lineWidth} snapping={snapping} touchDraw={touchDraw} selected={selected} onSelect={setSelected} onChange={change} onScale={p=>{setScalePoints(p);setEntry('5000');setDialog('scale');}} onText={p=>{setTextPoint(p);setEntry('');setDialog('text');}} onTool={setTool} onHint={setMessage} svgRef={svgRef} fitSignal={fitSignal}/>
 <div className="canvas-footer"><div className="button-row"><button onClick={plan.undo} disabled={!plan.canUndo} aria-label="元に戻す"><Undo2 size={19}/></button><button onClick={plan.redo} disabled={!plan.canRedo} aria-label="やり直す"><Redo2 size={19}/></button></div><span>{tool==='scale'?'既知の寸法の両端を順に押してください':toolMeta?.hint}</span><button aria-label="設定を表示" className="canvas-settings" onClick={()=>setPanel(v=>!v)}><Settings2 size={18}/></button></div></div>
 {panel&&<aside className="inspector"><div className="inspector-title"><h2>{tool==='scale'?'基準寸法':toolMeta?.label}</h2><button aria-label="設定パネルを閉じる" onClick={()=>setPanel(false)}><X size={18}/></button></div>
 {tool==='scale'&&<div className="instruction">寸法が分かる2点を選び、実際の長さを入力します。<small>{scaleTarget==='underlay'?'下絵だけを補正します。配置済みの線・部品の実寸は変えません。':doc.calibrated&&doc.elements.length?'校正済みの案件は別案を作り、図面全体の縮尺を補正します。元の案件は残ります。':'下絵と未校正の手描きを同じ倍率で補正します。'}</small></div>}
 {tool==='clean'&&<label className="field"><span>描く形</span><select value={figure} onChange={e=>setFigure(e.target.value as typeof figure)}><option value="line">直線</option><option value="polyline">折れ線</option><option value="rect">長方形</option><option value="ellipse">円・楕円</option><option value="area">多角形の面</option></select></label>}
 {tool==='part'&&<><div className="part-picker">{Object.entries(parts).map(([key,p])=><button key={key} aria-pressed={part===key} onClick={()=>setPart(key as Part)}>{p.name}<small>{p.w} × {p.h}</small></button>)}</div><p className="small-note">初期寸法は見本です。配置後に実物の寸法へ変更できます。</p></>}
 {['pen','clean','dimension','text'].includes(tool)&&<><div className="color-swatches">{colors.map(c=><button key={c} style={{background:c}} aria-label={'線色 '+c} aria-pressed={color===c} onClick={()=>setColor(c)}/>)}</div><div className="settings-row"><label className="field"><span>線・文字の色</span><input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label>{tool!=='text'&&<label className="field"><span>線の太さ</span><select value={lineWidth} onChange={e=>setLineWidth(Number(e.target.value))}><option value="15">細い</option><option value="25">標準</option><option value="50">太い</option><option value="120">マーカー</option></select></label>}</div></>}
 {picked&&<section className="selected-properties"><div className="eyebrow">選択した{picked.kind==='part'?parts[picked.part!].name:picked.kind==='stroke'?'手書き':picked.kind==='text'?'注記':'図形'}</div>
 <label className="check"><input type="checkbox" checked={!!picked.locked} onChange={e=>update({locked:e.target.checked})}/>この図形を固定</label>
 <fieldset className="property-fields" disabled={picked.locked}>{picked.size&&<div className="settings-row"><NumberField label="幅（mm）" value={picked.size.w} apply={n=>update({size:{...picked.size!,w:n}})}/><NumberField label="長さ（mm）" value={picked.size.h} apply={n=>update({size:{...picked.size!,h:n}})}/></div>}
 {['rect','ellipse','area'].includes(picked.kind)&&doc.calibrated&&<div className="settings-row"><NumberField label="図形の幅（mm）" value={bounds(picked).w} apply={n=>update(resizeElement(picked,n,bounds(picked).h))}/><NumberField label="図形の奥行（mm）" value={bounds(picked).h} apply={n=>update(resizeElement(picked,bounds(picked).w,n))}/></div>}
 {picked.kind==='part'&&<NumberField label="回転（度）" value={picked.rotation} min={-360} max={360} apply={n=>update({rotation:n})}/>}
 {['line','dimension'].includes(picked.kind)&&doc.calibrated&&<NumberField label="線の長さ（mm）" value={distance(picked.points[0],picked.points[1])} apply={n=>update(withLength(picked,n))}/>}
 {picked.kind==='text'&&<label className="field"><span>注記</span><textarea maxLength={200} value={picked.text} onChange={e=>update({text:e.target.value})}/></label>}
 {['rect','ellipse','area'].includes(picked.kind)&&<><label className="field"><span>仕上げ</span><select value={picked.material} onChange={e=>update({material:e.target.value as Material})}>{Object.entries(materials).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{doc.calibrated&&<p className="area-value">面積 {area(picked).toLocaleString('ja-JP',{maximumFractionDigits:2})} m²</p>}</>}
 <label className="field"><span>図形の濃さ {Math.round((picked.opacity??1)*100)}%</span><input type="range" min="10" max="100" value={(picked.opacity??1)*100} onChange={e=>update({opacity:Number(e.target.value)/100})}/></label>
 {picked.kind==='stroke'&&<button className="full" onClick={cleanSelected}>手描きを残して清書を作る</button>}
 <div className="object-actions"><button disabled={picked.locked} onClick={()=>update(rotateElement(picked,90))}><RotateCw size={16}/>90°</button><button onClick={duplicate}><Copy size={16}/>複製</button><button disabled={picked.locked} onClick={remove} aria-label="選択した要素を削除"><Trash2 size={17}/></button></div><div className="object-actions"><button onClick={()=>reorder(true)}><ArrowUp size={15}/>最前面</button><button onClick={()=>reorder(false)}><ArrowDown size={15}/>最背面</button></div></fieldset></section>}
 {!picked&&tool==='select'&&<div className="instruction">線・面・部品を押すと寸法や素材を変更できます。指でも選択・移動できます。</div>}
 <section className="layer-settings"><h3><Layers size={16}/> 表示</h3><label className="check"><input type="checkbox" checked={snapping} onChange={e=>setSnapping(e.target.checked)}/>端点・水平垂直・100mmに吸着</label>{doc.underlay&&<><label className="check"><input type="checkbox" checked={doc.underlay.visible} onChange={e=>change(d=>({...d,underlay:{...d.underlay!,visible:e.target.checked}}))}/>下絵を表示</label><label className="field"><span>下絵の濃さ {Math.round(doc.underlay.opacity*100)}%</span><input type="range" min="10" max="100" value={doc.underlay.opacity*100} onChange={e=>change(d=>({...d,underlay:{...d.underlay!,opacity:Number(e.target.value)/100}}),false)}/></label></>}
 {([['draft','手描き'],['design','清書・部品'],['dimensions','寸法・注記']] as const).map(([key,label])=><label className="check" key={key}><input type="checkbox" checked={doc.layers[key]} onChange={e=>change(d=>({...d,layers:{...d.layers,[key]:e.target.checked}}),false)}/>{label}</label>)}
 {doc.layers.draft&&<label className="field"><span>手描きの濃さ {Math.round(doc.draftOpacity*100)}%</span><input type="range" min="10" max="100" value={doc.draftOpacity*100} onChange={e=>change(d=>({...d,draftOpacity:Number(e.target.value)/100}),false)}/></label>}</section>
 <UnderlaySettings doc={doc} change={change} fail={fail} calibrate={()=>{setScaleTarget('underlay');setTool('scale');setPanel(false);setMessage('新しい下絵の、寸法が分かる2点を押してください。下絵だけを補正します');}}/>
 <section className="project-settings"><h3>案件・保存</h3><label className="field"><span>担当者</span><input value={doc.owner||''} maxLength={100} onChange={e=>change(d=>({...d,owner:e.target.value}),false)}/></label><p className="small-note" role="status">{cloud.available?cloudText:cloud.publicPreview?'開発中：この端末に自動保存。バックアップZIPで引き継げます。':'端末保存中。クラウド接続は準備中です。'}</p><div className="inspector-end"><button onClick={duplicatePlan}><Copy size={16}/>別案</button><button onClick={()=>void plan.flush().catch(fail)}><Save size={16}/>保存</button></div><button className="full" onClick={()=>void runSync(true)}>同期・再取得</button><button className="full" disabled={!cloud.available} onClick={()=>void showHistory()}>クラウドの保存履歴</button><button className="full" onClick={()=>{change(d=>({...d,archived:!d.archived}));void toList();}}><Archive size={16}/>{doc.archived?'アーカイブから戻す':'案件をアーカイブ'}</button></section></aside>}</main>
 <footer className="app-footer"><span>{doc.elements.length} 要素 · {doc.calibrated?'基準寸法 設定済み':'寸法未設定'} · {doc.calibrated&&doc.underlay?.scaleVerified===false?'下絵の縮尺 要確認':'下絵は固定'}</span><span>{cloud.available?cloudText:'端末に自動保存 · バックアップも保管してください'}</span></footer></>}
 {source&&<Modal title="下絵を取り込む" close={()=>void closeSource()}><SourceDialog source={source} hasPlan={route==='editor'&&!!doc} apply={applySource} cancel={()=>void closeSource()}/></Modal>}
 {dialog&&<Modal title={{new:'白紙から始める',scale:scaleTarget==='underlay'?'下絵だけの基準寸法':'基準寸法を設定',text:'注記を追加',help:'使い方',export:'図面を出力',history:'保存履歴'}[dialog]} close={()=>setDialog(null)}>
 {['new','scale','text'].includes(dialog)&&<form onSubmit={e=>{e.preventDefault();void submitDialog();}}><label className="field"><span>{dialog==='new'?'案件名':dialog==='scale'?'選んだ2点の実際の長さ（mm）':'注記の内容'}</span>{dialog==='text'?<textarea autoFocus value={entry} maxLength={200} onChange={e=>setEntry(e.target.value)}/>:<input autoFocus type={dialog==='scale'?'number':'text'} min={dialog==='scale'?1:undefined} max={dialog==='scale'?1000000:undefined} value={entry} maxLength={120} required={dialog!=='new'} onChange={e=>setEntry(e.target.value)}/>}</label>{dialog==='scale'&&<p className="small-note">5mなら「5000」。{scaleTarget==='underlay'?'下絵だけを補正します。線・部品の実寸は変えません。':doc?.calibrated&&doc.elements.length?'元の案件を残し、別案で図面全体を補正します。':'下絵と未校正の線を同じ倍率で補正します。'}</p>}<button className="primary full" type="submit">確定</button></form>}
 {dialog==='help'&&<><ol className="help-list"><li>「下絵から始める」でPDFや画像を選びます。</li><li>ページ・向き・余白を確認し、下絵を取り込みます。</li><li>ペンで描き、「基準寸法」で実寸を合わせます。</li><li>清書・素材・部品・寸法・注記を加えます。</li><li>保存状態を確認し、出力プレビューからPDFを保存します。</li></ol><p>Apple Pencilは描画、選択モードの指は選択・移動。2本指は移動・拡大縮小です。ペンがない場合は「指で描く」をONにします。</p><p>iPadではSafariの共有メニューから「ホーム画面に追加」すると、アプリとして開けます。新しく開くときは通信が必要です。開いている案件は通信が切れても端末保存を続けます。</p><p>Ctrl / ⌘ + Z：元に戻す。Shiftを加えるとやり直し。Delete：選択した要素を削除。</p><p className="small-note">端末のブラウザーデータを消す前に、同期完了とバックアップを確認してください。Apple Pencil実機の検証状況は納品ガイドを参照してください。</p></>}
 {dialog==='export'&&doc&&<><p>内容を確認してから保存します。手描きも初期設定で含めます。</p><div className="settings-row"><label className="field"><span>用紙</span><select value={pdfSize} onChange={e=>setPdfSize(e.target.value as 'A4'|'A3')}><option value="A4">A4 横</option><option value="A3">A3 横</option></select></label><label className="field"><span>形式</span><select value={format} onChange={e=>setFormat(e.target.value as typeof format)}><option value="pdf">PDF</option><option value="png">PNG画像</option></select></label></div>
 <label className="check"><input type="checkbox" checked={includeDraft} onChange={e=>setIncludeDraft(e.target.checked)}/>表示中の手描きを含める</label><button className="primary full" onClick={()=>void makeOutput()} disabled={!!busy}>出力プレビューを作る</button>{output&&<><div className="source-preview"><img src={output.preview} alt="出力する図面のプレビュー"/></div><button className="primary full" onClick={()=>void shareOrDownload(output.blob,output.name).catch(fail)}><Download size={18}/>{format==='pdf'?'PDF':'画像'}を保存</button>{!!navigator.share&&<button className="full" onClick={()=>void shareOrDownload(output.blob,output.name,true).catch(e=>{if(e?.name!=='AbortError')fail(e);})}>共有メニューを開く</button>}</>}
 {!doc.calibrated&&<p className="small-note">「寸法未設定」と明記して出力します。</p>}<button className="full" onClick={()=>void exportBackup(doc).catch(fail)}><FileJson size={18}/>原本付き編集データをバックアップ</button><p className="small-note">表示しているレイヤーが対象です。印刷縮尺は固定していません。編集データは後から再編集できます。</p></>}
 {dialog==='history'&&<><p>直近10版を保持します。復元すると別案を作成し、現在の案件も残します。</p>{versions.map(v=><button className="full" key={v.revision} onClick={()=>void restore(v.payload)}>版{v.revision} · {new Date(v.updated).toLocaleString('ja-JP')} を別案で開く</button>)}{!versions.length&&<p>まだクラウドの保存履歴がありません。</p>}<button className="full" onClick={()=>void maintenance().then(()=>setMessage('履歴から参照されない一時ファイルを整理しました')).catch(fail)}>不要になった同期用一時ファイルを整理</button></>}
 </Modal>}
 {busy&&<div className="busy-overlay" role="status" aria-live="polite"><span>{busy}…</span></div>}
 </div>;
}
