import {type Element,type Plan,distance,formatMM,bounds} from './model';
export function Patterns(){return <defs><pattern id="gravel" width="110" height="110" patternUnits="userSpaceOnUse"><rect width="110" height="110" fill="#f3eee4"/><circle cx="20" cy="24" r="8" fill="#9b9589"/><circle cx="82" cy="82" r="6" fill="#bab3a6"/></pattern><pattern id="grass" width="180" height="180" patternUnits="userSpaceOnUse"><rect width="180" height="180" fill="#dce8cd"/><path d="M50 110l20-35 20 35" fill="none" stroke="#9eb389" strokeWidth="10"/></pattern><pattern id="tile" width="600" height="600" patternUnits="userSpaceOnUse"><rect width="600" height="600" fill="#d8c9b1"/><path d="M0 0H600V600" fill="none" stroke="#fff" strokeWidth="18"/></pattern><pattern id="wood" width="180" height="800" patternUnits="userSpaceOnUse"><rect width="180" height="800" fill="#b89770"/><path d="M0 0V800 M20 0V800" stroke="#94734f" strokeWidth="9"/></pattern><pattern id="water" width="300" height="240" patternUnits="userSpaceOnUse"><rect width="300" height="240" fill="#cae0e6"/><path d="M0 130Q75 70 150 130T300 130" stroke="#92bcc8" strokeWidth="15" fill="none"/></pattern></defs>;}
export function Shape({e,selected=false,hit=true,scale=1}:{e:Element;selected?:boolean;hit?:boolean;scale?:number}){
 const p=e.points[0],b=bounds(e),stroke=e.color,fill=e.material==='grass'?'url(#grass)':e.material==='gravel'?'url(#gravel)':e.material==='concrete'?'#e3e5df':e.material==='tile'?'url(#tile)':e.material==='wood'?'url(#wood)':e.material==='water'?'url(#water)':'none',line=e.points.map(v=>v.x+','+v.y).join(' ');
 let graphic;
 if(e.kind==='part'&&e.size){const w=e.size.w,h=e.size.h;graphic=<g transform={'translate('+p.x+' '+p.y+') rotate('+e.rotation+')'}>{e.part==='car'?<><rect x={-w/2} y={-h/2} width={w} height={h} rx={w*.2} fill="#fafbf7" stroke={stroke} strokeWidth="24"/><path d={'M'+(-w*.38)+' '+(-h*.27)+' Q0 '+(-h*.37)+' '+w*.38+' '+(-h*.27)+' L'+w*.33+' '+(-h*.1)+' H'+(-w*.33)+' Z M'+(-w*.33)+' '+h*.26+' H'+w*.33+' L'+w*.37+' '+h*.4+' Q0 '+h*.45+' '+(-w*.37)+' '+h*.4+' Z'} fill="#dae0da" stroke={stroke} strokeWidth="15"/><path d={'M'+(-w*.38)+' '+(-h*.06)+' V'+h*.2+' M'+w*.38+' '+(-h*.06)+' V'+h*.2} stroke={stroke} strokeWidth="15"/></>:e.part==='tree'?<><ellipse rx={w/2} ry={h/2} fill="#cadfba" stroke="#54754c" strokeWidth="22"/><path d={'M0 '+(-h*.36)+' V'+h*.36+' M'+(-w*.28)+' '+(-h*.2)+' L'+w*.3+' '+h*.2+' M'+(-w*.3)+' '+h*.2+' L'+w*.28+' '+(-h*.2)} stroke="#68855f" strokeWidth="18"/></>:e.part==='gate'?<rect x={-w/2} y={-h/2} width={w} height={h} fill="#c7b995" stroke={stroke} strokeWidth="22"/>:e.part==='person'?<><ellipse rx={w*.48} ry={h*.26} fill="#80928b" stroke={stroke} strokeWidth="16"/><circle cy={-h*.16} r={w*.25} fill="#dbbba0" stroke={stroke} strokeWidth="16"/></>:e.part==='bicycle'?<><ellipse cy={-h*.32} rx={w*.16} ry={h*.17} fill="none" stroke={stroke} strokeWidth="30"/><ellipse cy={h*.32} rx={w*.16} ry={h*.17} fill="none" stroke={stroke} strokeWidth="30"/><path d={'M0 '+(-h*.38)+'V'+h*.34+' M'+(-w*.45)+' '+(-h*.25)+'H'+w*.45+' M'+(-w*.23)+' '+h*.12+'H'+w*.23} stroke={stroke} strokeWidth="32"/></>:e.part==='stairs'||e.part==='deck'?<><rect x={-w/2} y={-h/2} width={w} height={h} fill={e.part==='deck'?'url(#wood)':'#e4e2da'} stroke={stroke} strokeWidth="24"/>{e.part==='stairs'&&[1,2,3].map(i=><line key={i} x1={-w/2} x2={w/2} y1={-h/2+h*i/4} y2={-h/2+h*i/4} stroke={stroke} strokeWidth="20"/>)}</>:<><ellipse rx={w*.31} ry={h*.31} fill="#cbbf9e" stroke="#746e5e" strokeWidth="20"/><path d={'M'+(-w*.45)+' '+(-h*.15)+' V'+h*.15+' M'+w*.45+' '+(-h*.15)+' V'+h*.15+' M'+(-w*.15)+' '+(-h*.45)+' H'+w*.15+' M'+(-w*.15)+' '+h*.45+' H'+w*.15} stroke="#8f896e" strokeWidth={Math.min(w,h)*.09}/></>}</g>;}
 else if(e.kind==='text')graphic=<text x={p.x} y={p.y} dominantBaseline="hanging" fontFamily="sans-serif" fontSize="220" fill={stroke}>{(e.text||'').split('\n').map((line,i)=><tspan key={i} x={p.x} dy={i?280:0}>{line}</tspan>)}</text>;
 else if(e.kind==='rect')graphic=<rect x={b.x} y={b.y} width={b.w} height={b.h} fill={fill} stroke={stroke} strokeWidth={e.width}/>;
 else if(e.kind==='ellipse')graphic=<ellipse cx={b.x+b.w/2} cy={b.y+b.h/2} rx={b.w/2} ry={b.h/2} fill={fill} stroke={stroke} strokeWidth={e.width}/>;
 else if(e.kind==='area')graphic=<polygon points={line} fill={fill==='none'?'#eff2e8':fill} stroke={stroke} strokeWidth={e.width} strokeLinejoin="round"/>;
 else graphic=<><polyline points={line} fill="none" stroke={stroke} strokeWidth={e.width} strokeLinecap="round" strokeLinejoin="round"/>{hit&&<polyline points={line} fill="none" stroke="transparent" strokeWidth={Math.max(e.width,14*scale)} data-editor-only="true"/>}{e.kind==='dimension'&&e.points[1]&&<><text x={(p.x+e.points[1].x)/2} y={(p.y+e.points[1].y)/2-80} textAnchor="middle" fontFamily="sans-serif" fontSize={Math.max(210,12*scale)} fill={stroke} stroke="#fff" strokeWidth="40" paintOrder="stroke">{formatMM(distance(p,e.points[1]))} mm</text>{e.points.map((v,i)=><circle key={i} cx={v.x} cy={v.y} r="32" fill={stroke}/>)}</>}</>;
 return <g data-element={e.id} data-kind={e.kind} opacity={e.opacity??1}>{graphic}{selected&&!e.locked&&<g data-editor-only="true"><rect x={b.x-5*scale} y={b.y-5*scale} width={Math.max(b.w,scale*10)+10*scale} height={Math.max(b.h,scale*10)+10*scale} fill="none" stroke="#237653" strokeWidth={1.5*scale} strokeDasharray={5*scale+' '+4*scale} pointerEvents="none"/>{['line','polyline','rect','ellipse','area','dimension'].includes(e.kind)&&e.points.map((v,i)=><g key={i} data-vertex={i} data-element={e.id}><circle cx={v.x} cy={v.y} r={17*scale} fill="transparent"/><circle cx={v.x} cy={v.y} r={5*scale} fill="#fff" stroke="#237653" strokeWidth={2*scale}/></g>)}</g>}</g>;
}
export function Content({doc,selected,draft,scale=1,hit=true}:{doc:Plan;selected?:string;draft?:Element|null;scale?:number;hit?:boolean}){
 const visible=(e:Element)=>e.kind==='stroke'?doc.layers.draft:e.kind==='dimension'||e.kind==='text'?doc.layers.dimensions:doc.layers.design;
 return <><Patterns/>{doc.underlay?.visible&&<image href={doc.underlay.src} transform={'translate('+(doc.underlay.x||0)+' '+(doc.underlay.y||0)+') rotate('+(doc.underlay.rotation||0)+')'} x="0" y="0" width={doc.underlay.width} height={doc.underlay.height} opacity={doc.underlay.opacity} pointerEvents="none"/>}{doc.elements.filter(visible).map(e=><g key={e.id} opacity={e.kind==='stroke'?doc.draftOpacity:1}><Shape e={draft?.id===e.id?draft:e} selected={e.id===selected} scale={scale} hit={hit}/></g>)}{draft&&!doc.elements.some(e=>e.id===draft.id)&&<Shape e={draft} scale={scale} hit={false}/>}</>;
}
