export type Point={x:number;y:number};
export type Kind='stroke'|'line'|'polyline'|'rect'|'ellipse'|'area'|'dimension'|'part'|'text';
export type Part='car'|'tree'|'gate'|'table'|'person'|'bicycle'|'stairs'|'deck';
export type Material='none'|'concrete'|'grass'|'gravel'|'tile'|'wood'|'water';
export type Element={id:string;kind:Kind;points:Point[];color:string;width:number;material:Material;part?:Part;size?:{w:number;h:number};rotation:number;text?:string;opacity?:number;locked?:boolean};
export type Underlay={src:string;name:string;width:number;height:number;opacity:number;visible:boolean;x?:number;y?:number;rotation?:number;assetId?:string;page?:number;scaleVerified?:boolean};
export type Plan={schema:1|2;id:string;name:string;updatedAt:string;revision:number;calibrated:boolean;calibration?:{points:Point[];length:number};underlay?:Underlay;elements:Element[];layers:{draft:boolean;design:boolean;dimensions:boolean};draftOpacity:number;owner?:string;archived?:boolean};
export const materials:Record<Material,string>={none:'なし',concrete:'土間コンクリート',grass:'芝',gravel:'砂利',tile:'タイル',wood:'ウッドデッキ',water:'水面'};
export const parts:Record<Part,{name:string;w:number;h:number}>={car:{name:'車',w:1800,h:4800},tree:{name:'植栽',w:1200,h:1200},gate:{name:'門柱',w:600,h:200},table:{name:'テーブル',w:1800,h:1800},person:{name:'人',w:500,h:650},bicycle:{name:'自転車',w:600,h:1800},stairs:{name:'階段',w:1800,h:1200},deck:{name:'デッキ',w:3000,h:1800}};
export const uid=()=>crypto.randomUUID();
export const distance=(a:Point,b:Point)=>Math.hypot(b.x-a.x,b.y-a.y);
export const formatMM=(n:number)=>Math.round(n).toLocaleString('ja-JP');
export function newPlan(name='新しい外構プラン'):Plan{return {schema:2,id:uid(),name,updatedAt:new Date().toISOString(),revision:0,calibrated:true,elements:[],layers:{draft:true,design:true,dimensions:true},draftOpacity:.8,owner:'',archived:false};}
export function element(kind:Kind,points:Point[]):Element{return {id:uid(),kind,points,color:'#303e34',width:25,material:'none',rotation:0};}
export function partAt(part:Part,p:Point):Element{return {...element('part',[p]),part,size:{w:parts[part].w,h:parts[part].h}};}
export function moved(e:Element,dx:number,dy:number):Element{return {...e,points:e.points.map(p=>({x:p.x+dx,y:p.y+dy}))};}
export function withLength(e:Element,length:number):Element {if(!Number.isFinite(length)||length<=0||length>1000000||e.points.length!==2)throw Error('長さは1〜1,000,000 mmで入力してください');const [a,b]=e.points,d=distance(a,b);if(d<.01)throw Error('長さがない線は変更できません');return {...e,points:[a,{x:a.x+(b.x-a.x)*length/d,y:a.y+(b.y-a.y)*length/d}]};}
export function snap(p:Point,start?:Point,enabled=true):Point{if(!enabled)return p;const r={x:Math.round(p.x/100)*100,y:Math.round(p.y/100)*100};if(start){const dx=r.x-start.x,dy=r.y-start.y;if(Math.abs(dy)<Math.abs(dx)*.12)r.y=start.y;else if(Math.abs(dx)<Math.abs(dy)*.12)r.x=start.x;}return r;}
function box(pts:Point[]){let x=Infinity,y=Infinity,r=-Infinity,b=-Infinity;for(const p of pts){x=Math.min(x,p.x);y=Math.min(y,p.y);r=Math.max(r,p.x);b=Math.max(b,p.y);}return {x,y,w:Math.max(1,r-x),h:Math.max(1,b-y)};}
export function bounds(e:Element){let pts=e.points;if(e.kind==='part'&&e.size){const p=e.points[0],a=e.rotation*Math.PI/180;pts=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,y])=>({x:p.x+x*e.size!.w/2*Math.cos(a)-y*e.size!.h/2*Math.sin(a),y:p.y+x*e.size!.w/2*Math.sin(a)+y*e.size!.h/2*Math.cos(a)}));}if(e.kind==='text'){const rows=(e.text||'').split('\n');pts=[e.points[0],{x:e.points[0].x+Math.max(...rows.map(s=>s.length),1)*220,y:e.points[0].y+rows.length*280}];}const b=box(pts);if(e.kind==='dimension')return {x:b.x-300,y:b.y-400,w:b.w+600,h:b.h+800};return b;}
export function underlayBounds(u:Underlay){const a=(u.rotation||0)*Math.PI/180;return box([[0,0],[u.width,0],[u.width,u.height],[0,u.height]].map(([x,y])=>({x:(u.x||0)+x*Math.cos(a)-y*Math.sin(a),y:(u.y||0)+x*Math.sin(a)+y*Math.cos(a)})));}
export function visible(e:Element,doc:Plan){return e.kind==='stroke'?doc.layers.draft:e.kind==='dimension'||e.kind==='text'?doc.layers.dimensions:doc.layers.design;}
export function planBounds(doc:Plan,shownOnly=false){const boxes=doc.elements.filter(e=>!shownOnly||visible(e,doc)).map(bounds);if(doc.underlay&&(!shownOnly||doc.underlay.visible))boxes.push(underlayBounds(doc.underlay));if(!boxes.length)return {x:0,y:0,w:12000,h:10000};return box(boxes.flatMap(b=>[{x:b.x-100,y:b.y-100},{x:b.x+b.w+100,y:b.y+b.h+100}]));}
export function calibrated(doc:Plan,a:Point,b:Point,length:number):Plan {const d=distance(a,b);if(d<10||!Number.isFinite(length)||length<1||length>1000000)throw Error('離れた2点を選び、実寸を1〜1,000,000 mmで入力してください');const k=length/d,point=(p:Point)=>({x:p.x*k,y:p.y*k});return {...doc,calibrated:true,calibration:{points:[point(a),point(b)],length},underlay:doc.underlay?{...doc.underlay,x:(doc.underlay.x||0)*k,y:(doc.underlay.y||0)*k,width:doc.underlay.width*k,height:doc.underlay.height*k,scaleVerified:true}:undefined,elements:doc.elements.map(e=>({...e,points:e.points.map(point),width:e.width*k,size:e.size?{w:e.size.w*k,h:e.size.h*k}:undefined}))};}
export function area(e:Element){if(e.kind==='rect')return Math.abs((e.points[1].x-e.points[0].x)*(e.points[1].y-e.points[0].y))/1e6;if(e.kind==='ellipse')return Math.PI*Math.abs((e.points[1].x-e.points[0].x)*(e.points[1].y-e.points[0].y))/4e6;if(e.kind!=='area')return 0;return Math.abs(e.points.reduce((n,p,i)=>{const q=e.points[(i+1)%e.points.length];return n+p.x*q.y-q.x*p.y;},0))/2e6;}
export function rotateElement(e:Element,degrees:number){if(e.kind==='part')return {...e,rotation:(e.rotation+degrees)%360};const b=bounds(e),c={x:b.x+b.w/2,y:b.y+b.h/2},a=degrees*Math.PI/180;const points=e.kind==='rect'?[e.points[0],{x:e.points[1].x,y:e.points[0].y},e.points[1],{x:e.points[0].x,y:e.points[1].y}]:e.points;return {...e,kind:e.kind==='rect'?'area' as Kind:e.kind,points:points.map(p=>({x:c.x+(p.x-c.x)*Math.cos(a)-(p.y-c.y)*Math.sin(a),y:c.y+(p.x-c.x)*Math.sin(a)+(p.y-c.y)*Math.cos(a)}))};}
export function cleanStroke(e:Element):Element {if(e.kind!=='stroke'||e.points.length<2)return e;const first=e.points[0],last=e.points[e.points.length-1],b=box(e.points),closed=distance(first,last)<Math.max(b.w,b.h)*.18;if(closed){const points=[{x:b.x,y:b.y},{x:b.x+b.w,y:b.y+b.h}];const cx=b.x+b.w/2,cy=b.y+b.h/2,roundness=e.points.reduce((sum,p)=>sum+Math.abs(Math.hypot((p.x-cx)/(b.w/2),(p.y-cy)/(b.h/2))-1),0)/e.points.length;return {...e,kind:roundness<.12?'ellipse':'rect',points,material:'none'};}const simplified=simplify(e.points,Math.max(20,Math.max(b.w,b.h)*.025));return {...e,kind:simplified.length===2?'line':'polyline',points:simplified};}
export function simplify(points:Point[],tolerance:number):Point[]{if(points.length<=2)return points;const result=[points[0]];const stack:[[number,number]]|[number,number][]=[[0,points.length-1]],keep=new Set([0,points.length-1]);while(stack.length){const [a,b]=stack.pop()!;let max=tolerance,index=-1;const p=points[a],q=points[b],dx=q.x-p.x,dy=q.y-p.y,den=dx*dx+dy*dy;for(let i=a+1;i<b;i++){const t=den?Math.max(0,Math.min(1,((points[i].x-p.x)*dx+(points[i].y-p.y)*dy)/den)):0;const d=distance(points[i],{x:p.x+t*dx,y:p.y+t*dy});if(d>max){max=d;index=i;}}if(index>=0){keep.add(index);stack.push([a,index],[index,b]);}}result.length=0;for(const i of [...keep].sort((a,b)=>a-b))result.push(points[i]);return result;}
function obj(v:unknown):v is Record<string,unknown>{return typeof v==='object'&&v!==null&&!Array.isArray(v);}
function num(v:unknown,min=-1e7,max=1e7):v is number{return typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;}
function point(v:unknown):v is Point{return obj(v)&&num(v.x)&&num(v.y);}
export function validatePlan(raw:unknown):Plan{
 if(!obj(raw)||(raw.schema!==1&&raw.schema!==2)||!num(raw.revision,0,1e9)||!Number.isInteger(raw.revision)||typeof raw.updatedAt!=='string'||!Number.isFinite(Date.parse(raw.updatedAt))||typeof raw.id!=='string'||!raw.id||raw.id.length>100||typeof raw.name!=='string'||raw.name.length>120||!Array.isArray(raw.elements)||raw.elements.length>3000||typeof raw.calibrated!=='boolean'||!num(raw.draftOpacity,0,1)||!obj(raw.layers)||!['draft','design','dimensions'].every(k=>typeof (raw.layers as Record<string,unknown>)[k]==='boolean'))throw Error('対応していない図面データです');
 if(raw.owner!==undefined&&(typeof raw.owner!=='string'||raw.owner.length>100))throw Error('担当者が正しくありません');if(raw.archived!==undefined&&typeof raw.archived!=='boolean')throw Error('案件の状態が正しくありません');
 let total=0;const ids=new Set<string>();for(const e of raw.elements){if(!obj(e)||typeof e.id!=='string'||!e.id||e.id.length>100||ids.has(e.id)||!['stroke','line','polyline','rect','ellipse','area','dimension','part','text'].includes(String(e.kind))||!Array.isArray(e.points)||e.points.length<1||e.points.length>20000||!e.points.every(point)||!num(e.width,.01,1e6)||!num(e.rotation,-36000,36000)||typeof e.color!=='string'||!/^#[0-9a-f]{6}$/i.test(e.color)||!Object.hasOwn(materials,String(e.material)))throw Error('図形データが正しくありません');
 ids.add(e.id);total+=e.points.length;if(e.opacity!==undefined&&!num(e.opacity,0,1))throw Error('透明度が正しくありません');if(e.locked!==undefined&&typeof e.locked!=='boolean')throw Error('固定状態が正しくありません');
 if(['line','rect','ellipse','dimension'].includes(String(e.kind))&&e.points.length!==2)throw Error('線の点数が正しくありません');if(e.kind==='polyline'&&e.points.length<2)throw Error('折れ線には2点以上が必要です');if(e.kind==='area'&&e.points.length<3)throw Error('面には3点以上が必要です');
 if(e.kind==='part'&&(!Object.hasOwn(parts,String(e.part))||!obj(e.size)||!num(e.size.w,1,1e6)||!num(e.size.h,1,1e6)||e.points.length!==1))throw Error('部品の寸法が正しくありません');if(e.kind==='text'&&(typeof e.text!=='string'||e.text.length>200||e.points.length!==1))throw Error('注記が正しくありません');}
 if(total>200000)throw Error('図形の点数が多すぎます');
 if(raw.underlay!==undefined){const u=raw.underlay;if(!obj(u)||typeof u.src!=='string'||u.src.length>28e6||!/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(u.src)||!num(u.width,1,1e6)||!num(u.height,1,1e6)||!num(u.opacity,0,1)||typeof u.visible!=='boolean'||typeof u.name!=='string'||u.name.length>255)throw Error('元図面の形式が正しくありません');for(const k of ['x','y','rotation'])if(u[k]!==undefined&&!num(u[k]))throw Error('下絵の位置が正しくありません');if(u.assetId!==undefined&&(typeof u.assetId!=='string'||!/^[a-zA-Z0-9_-]{1,100}$/.test(u.assetId)))throw Error('原本の識別子が正しくありません');if(u.scaleVerified!==undefined&&typeof u.scaleVerified!=='boolean')throw Error('下絵の縮尺状態が正しくありません');if(u.page!==undefined&&(!num(u.page,1,10000)||!Number.isInteger(u.page)))throw Error('ページ番号が正しくありません');}
 if(raw.calibration!==undefined){const c=raw.calibration;if(!obj(c)||!Array.isArray(c.points)||c.points.length!==2||!c.points.every(point)||!num(c.length,1,1e6))throw Error('基準寸法が正しくありません');}
 return {...structuredClone(raw),schema:2} as Plan;
}

export function resizeElement(e:Element,w:number,h:number):Element {if(!Number.isFinite(w)||!Number.isFinite(h)||w<1||h<1||w>1e6||h>1e6)throw Error('寸法は1〜1,000,000 mmで入力してください');const b=bounds(e);return {...e,points:e.points.map(p=>({x:b.x+(p.x-b.x)*w/b.w,y:b.y+(p.y-b.y)*h/b.h}))};}

export function calibrateUnderlay(doc:Plan,a:Point,b:Point,length:number):Plan {if(!doc.underlay)throw Error('下絵がありません');const gap=distance(a,b);if(gap<10||!Number.isFinite(length)||length<1||length>1e6)throw Error('離れた2点を選び、実寸を1〜1,000,000 mmで入力してください');const k=length/gap,u=doc.underlay;return {...doc,underlay:{...u,x:a.x+((u.x||0)-a.x)*k,y:a.y+((u.y||0)-a.y)*k,width:u.width*k,height:u.height*k,scaleVerified:true}};}
