import {useState} from 'react';
import {type Plan,type Underlay} from './model';
import {getOriginal} from './storage';
import {download} from './io';
export function UnderlaySettings({doc,change,fail,calibrate}:{calibrate:()=>void;doc:Plan;change:(f:(p:Plan)=>Plan,record?:boolean)=>void;fail:(e:unknown)=>void}){
 const [adjust,setAdjust]=useState(false);const u=doc.underlay;if(!u)return null;
 const patch=(p:Partial<Underlay>)=>change(d=>({...d,underlay:{...d.underlay!,...p}}));
 const original=async()=>{try{const f=u.assetId?await getOriginal(u.assetId):undefined;if(!f)throw Error('この旧案件には原本が残っていません。下絵は編集データに含まれています');download(f.blob,f.name);}catch(e){fail(e);}};
 return <section className="underlay-settings"><h3>下絵</h3>{doc.calibrated&&u.scaleVerified===false&&<p className="inline-error">差し替えた下絵の縮尺を確認してください。既存の図形の実寸は保持しています。</p>}{doc.calibrated&&<button className="full" onClick={calibrate}>下絵だけの基準寸法を合わせる</button>}<p className="small-note source-name">{u.name}</p><label className="check"><input type="checkbox" checked={adjust} onChange={e=>setAdjust(e.target.checked)}/>下絵の位置・大きさを調整</label>{adjust&&<><p className="small-note">描いた線・部品の実寸は変わりません。下絵だけを動かします。</p><div className="settings-row">{(['x','y'] as const).map(key=><label className="field" key={key}><span>{key==='x'?'横位置':'縦位置'}（mm）</span><input type="number" key={String(u[key])} defaultValue={Math.round(u[key]||0)} step="100" onBlur={e=>{const n=Number(e.target.value);if(Number.isFinite(n)&&Math.abs(n)<1e7)patch({[key]:n});else e.target.value=String(u[key]||0);}}/></label>)}</div><label className="field"><span>下絵の幅（mm）</span><input type="number" key={u.width} defaultValue={Math.round(u.width)} min="1" max="1000000" onBlur={e=>{const n=Number(e.target.value);if(n>0&&n<=1e6)patch({width:n,height:u.height*n/u.width,scaleVerified:false});else e.target.value=String(Math.round(u.width));}}/></label><div className="button-row"><button onClick={()=>patch({rotation:((u.rotation||0)+270)%360})}>左へ90°</button><button onClick={()=>patch({rotation:((u.rotation||0)+90)%360})}>右へ90°</button></div><button className="full" onClick={()=>{change(d=>({...d,underlay:undefined}));setAdjust(false);}}>下絵を外す（元に戻せます）</button></>}{u.assetId&&<button className="full" onClick={()=>void original()}>取り込んだ原本を保存</button>}</section>;
}
